version: '3'

services:
  withcpitch-bot:
    build: .
    container_name: withcpitch-bot
    restart: always
    volumes:
      - ./audio_cache:/app/audio_cache
      - ./temp:/app/temp
      - ./media:/app/media
    environment:
      - TOKEN=${TOKEN}
      - FFMPEG_PATH=/usr/bin/ffmpeg
